# Timer Plugin Configuration

# Timer settings
timer:
  # Initial value of the timer in days
  initial-days: 30.0

  # Maximum number of days allowed for the timer
  max-days: 30

  # Whether the timer is visible to players (true = visible, false = hidden)
  visible: true

  # Timer modification settings
  modification:
    # Maximum number of days a player can add at once (options: 1 or 2)
    max-add: 2

    # Maximum number of days a player can remove at once (options: 1 or 2)
    max-remove: 2

    # Minimum timer value required to allow day removal
    min-days-to-remove: 2

# Time Mace settings
time-mace:
  # Time Mace maximum dashes before cooldown
  max-dashes: 3

  # Time Mace cooldown in seconds
  cooldown: 120

  # Dash strength multiplier (higher = farther)
  dash-strength: 2.5

  # Time explosion settings
  explosion:
    # Explosion radius in blocks
    radius: 8

    # Duration of time distortion zone in seconds
    duration: 5

    # Slowness effect level (0-5)
    slowness-level: 3

    # Enable time explosion feature
    enabled: true

# Effects settings
effects:
  add-time:
    # Sound effect for adding time (BLOCK_BEACON_AMBIENT)
    sound: BLOCK_BEACON_AMBIENT
    # Volume for add time sound (0.0 to 1.0)
    sound-volume: 1.0
    # Pitch for add time sound (0.5 to 2.0)
    sound-pitch: 1.0
    # Duration of effects in seconds
    duration: 5

  remove-time:
    # Sound effect for removing time (ENTITY_ENDER_DRAGON_GROWL)
    sound: ENTITY_ENDER_DRAGON_GROWL
    # Volume for remove time sound (0.0 to 1.0)
    sound-volume: 1.0
    # Pitch for remove time sound (0.5 to 2.0)
    sound-pitch: 1.0
    # Duration of effects in seconds
    duration: 5

# Display settings
display:
  # Boss bar color (BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW)
  bar-color: BLUE

  # Boss bar style (SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20)
  bar-style: SOLID

  # Boss bar title format (use %d for days, %h for hours, %m for minutes)
  bar-title: "&6Time Remaining: &f%d days, %h hours, %m minutes"

# Messages
messages:
  # Message sent to killer when they receive the time modifier item
  killer-received-item: "&aYou've killed %victim%! Use the Heart of the Sea to modify the timer."

  # Message when the timer reaches zero
  timer-zero: "&cThe timer has reached zero!"

  # Message when player adds time to the timer
  player-added-time: "&a%player% added %days% day(s) to the timer!"

  # Message when player removes time from the timer
  player-removed-time: "&c%player% removed %days% day(s) from the timer!"

  # Message when timer is already at maximum days
  timer-at-max: "&cThe timer cannot exceed %max% days!"

  # Message when timer would go below 0
  timer-at-min: "&cThe timer cannot go below 0 days!"

  # Message when player is not a recent killer
  not-recent-killer: "&cYou can only use this item after killing a player."

  # Time Mace messages
  time-mace:
    dash: "&eYou dash forward! %dashes% dashes remaining."
    cooldown: "&cTime Mace is on cooldown. %time% seconds remaining."
    recharged: "&aTime Mace has been recharged! You have %dashes% dashes available."

# Item settings
time-modifier-item:
  # The display name of the time modifier item
  name: "&bTime Modifier"

  # The lore of the time modifier item
  lore:
    - "&eRight-click to open timer modification menu"
    - "&7Add or remove 1-2 days from the timer"
    - "&aKill players to earn these items"